# Generated by Django 5.2.17 on 2026-08-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('ssh_network', 'SSH Network'), ('openshift', 'OpenShift'), ('satellite', 'Red Hat Satellite'), ('ansible_aap', 'Ansible Automation Platform'), ('vcenter', 'VMware vCenter')], max_length=20)),
                ('hosts', models.JSONField(default=list)),
                ('port', models.IntegerField(default=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='credentials.credential')),
            ],
        ),
    ]
