# Generated by Django 5.2.17 on 2026-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('credential_type', models.CharField(choices=[('password', 'Username & Password'), ('ssh_key', 'SSH Key'), ('token', 'Token')], max_length=20)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_secret', models.TextField(blank=True, default='')),
                ('ssh_key_file', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
