import csv
import io
from collections import Counter
from scans.models import Scan, ScanResult
from reports.models import Report


def generate_report(scan: Scan) -> Report:
    results = ScanResult.objects.filter(scan=scan)
    successful = results.filter(status="success")
    failed = results.filter(status__in=["failed", "skipped"])

    os_counter = Counter()
    product_counter = Counter()
    for r in successful:
        os_name = r.data.get("os", "Unknown")
        if os_name:
            os_counter[os_name] += 1
        for product in r.data.get("products", []):
            product_counter[product] += 1

    summary = {
        "total_hosts": results.count(),
        "successful_hosts": successful.count(),
        "failed_hosts": failed.count(),
        "os_distribution": dict(os_counter),
        "products_found": dict(product_counter),
    }

    report = Report.objects.create(
        scan=scan,
        title="Health Check Report",
        summary=summary,
    )
    return report


def generate_csv(report: Report) -> str:
    results = ScanResult.objects.filter(scan=report.scan)
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["host", "source", "status", "os", "hostname", "kernel", "arch", "cpu_count", "memory_mb", "products", "error"])

    for r in results:
        writer.writerow([
            r.host,
            r.source.name,
            r.status,
            r.data.get("os", ""),
            r.data.get("hostname", ""),
            r.data.get("kernel", ""),
            r.data.get("arch", ""),
            r.data.get("cpu_count", ""),
            r.data.get("memory_mb", ""),
            ", ".join(r.data.get("products", [])),
            r.error_message,
        ])

    return output.getvalue()


def generate_pdf(report: Report) -> bytes:
    from weasyprint import HTML

    results = ScanResult.objects.filter(scan=report.scan)
    rows = ""
    for r in results:
        rows += f"""
        <tr>
            <td>{r.host}</td>
            <td>{r.status}</td>
            <td>{r.data.get('os', '')}</td>
            <td>{r.data.get('hostname', '')}</td>
            <td>{r.data.get('kernel', '')}</td>
            <td>{', '.join(r.data.get('products', []))}</td>
            <td>{r.error_message}</td>
        </tr>"""

    summary = report.summary
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Red Hat Display', Arial, sans-serif; margin: 40px; color: #151515; }}
            h1 {{ color: #ee0000; border-bottom: 3px solid #ee0000; padding-bottom: 10px; }}
            .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
            .card {{ background: #f0f0f0; padding: 20px; border-radius: 8px; min-width: 150px; text-align: center; }}
            .card .number {{ font-size: 32px; font-weight: bold; color: #151515; }}
            .card .label {{ font-size: 14px; color: #6a6e73; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #d2d2d2; padding: 8px 12px; text-align: left; font-size: 13px; }}
            th {{ background: #151515; color: white; }}
            tr:nth-child(even) {{ background: #f9f9f9; }}
            .footer {{ margin-top: 40px; font-size: 12px; color: #6a6e73; }}
        </style>
    </head>
    <body>
        <h1>Red Hat Health Check Report</h1>
        <div class="summary">
            <div class="card"><div class="number">{summary.get('total_hosts', 0)}</div><div class="label">Total Hosts</div></div>
            <div class="card"><div class="number">{summary.get('successful_hosts', 0)}</div><div class="label">Successful</div></div>
            <div class="card"><div class="number">{summary.get('failed_hosts', 0)}</div><div class="label">Failed</div></div>
        </div>
        <h2>Scan Results</h2>
        <table>
            <thead><tr><th>Host</th><th>Status</th><th>OS</th><th>Hostname</th><th>Kernel</th><th>Products</th><th>Error</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
        <div class="footer">Generated by Red Hat Health Check Tool</div>
    </body>
    </html>
    """
    return HTML(string=html_content).write_pdf()
